name: green_trail_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8

  # Network requests
  http: ^1.3.0

  # State management
  provider: ^6.1.4

  # Toast messages
  fluttertoast: ^8.2.1

  # Image picker
  image_picker: ^1.0.7

  # Env variables
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  fl_chart: ^0.70.2

  # TensorFlow Lite
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  permission_handler: ^11.3.0


  flutter_svg: ^2.0.7
  animations: ^2.0.7

  # Text-to-Speech
  flutter_tts: ^3.8.5  # Added missing flutter_tts package
  tflite_flutter: ^0.11.0
  image: ^4.1.3
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/home.jpg
    - assets/config/.env
    - assets/models/model_unquant.tflite
    - assets/models/labels.txt
